In [ ]:

#DEWTON KIPROP


In [4]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
import numpy as np

def load_iris_dataset(path):
    """Load the Iris dataset from a CSV file."""
    data = np.genfromtxt(path, delimiter=',', skip_header=1)
    X = data[:, :-1]  # Features
    y = data[:, -1]   # Target
    return X, y

# Path to the Iris dataset file
path_to_dataset = 'D:\\4.2 work\\ML\\Irislec.csv'  # Corrected file path

# Load the Iris dataset
X_train, y_train = load_iris_dataset(path_to_dataset)

# Print the loaded dataset
print("Features (X):")
print(X_train)
print("Target (y):")
print(y_train)


Features (X):
[[1.00e+00 5.10e+00 3.50e+00 1.40e+00 2.00e-01]
 [2.00e+00 4.90e+00 3.00e+00 1.40e+00 2.00e-01]
 [3.00e+00 4.70e+00 3.20e+00 1.30e+00 2.00e-01]
 [4.00e+00 4.60e+00 3.10e+00 1.50e+00 2.00e-01]
 [5.00e+00 5.00e+00 3.60e+00 1.40e+00 2.00e-01]
 [6.00e+00 5.40e+00 3.90e+00 1.70e+00 4.00e-01]
 [7.00e+00 4.60e+00 3.40e+00 1.40e+00 3.00e-01]
 [8.00e+00 5.00e+00 3.40e+00 1.50e+00 2.00e-01]
 [9.00e+00 4.40e+00 2.90e+00 1.40e+00 2.00e-01]
 [1.00e+01 4.90e+00 3.10e+00 1.50e+00 1.00e-01]
 [1.10e+01 5.40e+00 3.70e+00 1.50e+00 2.00e-01]
 [1.20e+01 4.80e+00 3.40e+00 1.60e+00 2.00e-01]
 [1.30e+01 4.80e+00 3.00e+00 1.40e+00 1.00e-01]
 [1.40e+01 4.30e+00 3.00e+00 1.10e+00 1.00e-01]
 [1.50e+01 5.80e+00 4.00e+00 1.20e+00 2.00e-01]
 [1.60e+01 5.70e+00 4.40e+00 1.50e+00 4.00e-01]
 [1.70e+01 5.40e+00 3.90e+00 1.30e+00 4.00e-01]
 [1.80e+01 5.10e+00 3.50e+00 1.40e+00 3.00e-01]
 [1.90e+01 5.70e+00 3.80e+00 1.70e+00 3.00e-01]
 [2.00e+01 5.10e+00 3.80e+00 1.50e+00 3.00e-01]
 [2.10e+01 5.40e+00 3.40e+

In [7]:
def euclidean_distance(point1, point2):
    """Calculate the Euclidean distance between two points."""
    return np.sqrt(np.sum((point1 - point2)**2))

# Loading the dataset from the CSV file
path_to_dataset = 'D:\\4.2 work\\ML\\Irislec.csv'
data = np.genfromtxt(path_to_dataset, delimiter=',', skip_header=1)

# Separating features (X) and target (y)
X = data[:, 1:-1]  # Features (excluding the first column which contains index and the last column which contains the target)
y = data[:, -1]    # Target

# New observation with the same number of features as the data points in X
new_observation = np.array([5.2, 3.1, 1.4, 0.2])  

# Computing Euclidean distances between the new observation and each data point in X
distances = [euclidean_distance(new_observation, x) for x in X]

# Printing the Euclidean distances
print("Euclidean distances between the new observation and each data point:")
for idx, distance in enumerate(distances, start=1):
    print(f"Distance to data point {idx}: {distance:.4f}")

Euclidean distances between the new observation and each data point:
Distance to data point 1: 0.4123
Distance to data point 2: 0.3162
Distance to data point 3: 0.5196
Distance to data point 4: 0.6083
Distance to data point 5: 0.5385
Distance to data point 6: 0.9000
Distance to data point 7: 0.6782
Distance to data point 8: 0.3742
Distance to data point 9: 0.8246
Distance to data point 10: 0.3317
Distance to data point 11: 0.6403
Distance to data point 12: 0.5385
Distance to data point 13: 0.4243
Distance to data point 14: 0.9592
Distance to data point 15: 1.1000
Distance to data point 16: 1.4107
Distance to data point 17: 0.8544
Distance to data point 18: 0.4243
Distance to data point 19: 0.9165
Distance to data point 20: 0.7211
Distance to data point 21: 0.4690
Distance to data point 22: 0.6481
Distance to data point 23: 0.8775
Distance to data point 24: 0.4796
Distance to data point 25: 0.7071
Distance to data point 26: 0.3000
Distance to data point 27: 0.4583
Distance to data point

In [8]:
# Ranking distances from nearest to furthest
sorted_indices = np.argsort(distances)

# Printing the ranked distances
print("Ranked distances from nearest to furthest:")
for rank, idx in enumerate(sorted_indices, start=1):
    print(f"Rank {rank}: Distance to data point {idx + 1}: {distances[idx]:.4f}")

Ranked distances from nearest to furthest:
Rank 1: Distance to data point 50: 0.2828
Rank 2: Distance to data point 29: 0.3000
Rank 3: Distance to data point 36: 0.3000
Rank 4: Distance to data point 26: 0.3000
Rank 5: Distance to data point 2: 0.3162
Rank 6: Distance to data point 38: 0.3317
Rank 7: Distance to data point 35: 0.3317
Rank 8: Distance to data point 10: 0.3317
Rank 9: Distance to data point 40: 0.3317
Rank 10: Distance to data point 8: 0.3742
Rank 11: Distance to data point 28: 0.4123
Rank 12: Distance to data point 1: 0.4123
Rank 13: Distance to data point 32: 0.4243
Rank 14: Distance to data point 18: 0.4243
Rank 15: Distance to data point 13: 0.4243
Rank 16: Distance to data point 46: 0.4243
Rank 17: Distance to data point 31: 0.4472
Rank 18: Distance to data point 27: 0.4583
Rank 19: Distance to data point 41: 0.4690
Rank 20: Distance to data point 21: 0.4690
Rank 21: Distance to data point 24: 0.4796
Rank 22: Distance to data point 37: 0.5099
Rank 23: Distance to da

In [10]:
def k_nearest_neighbors(X, y, new_observation, k=5):
    """Classify a new observation using k-nearest neighbors."""
    # Compute distances between the new observation and all data points
    distances = [euclidean_distance(new_observation, x) for x in X]
    
    # Getting indices of k nearest neighbors
    nearest_indices = np.argsort(distances)[:k]
    
    # Getting classes of k nearest neighbors
    nearest_classes = y[nearest_indices]
    
    # Checking if there are any missing values in the nearest classes
    if np.isnan(nearest_classes).any():
        # Handle missing values, e.g., return a default class
        predicted_class = "Default"
    else:
        # Finding the most common class among the nearest neighbors
        unique_classes, class_counts = np.unique(nearest_classes, return_counts=True)
        predicted_class = unique_classes[np.argmax(class_counts)]
    
    return predicted_class

# Classify the new observation using k-nearest neighbors with k=5
predicted_class = k_nearest_neighbors(X, y, new_observation, k=5)

print("Predicted class for the new observation:", predicted_class)


Predicted class for the new observation: Default
